// angular/src/app/components/cards/chat-card/chat-card.component.ts
import { Component } from '@angular/core';
import { Avatar } from '../../misc/avatar/avatar.component';
import { Team } from '../../team/team.component';
import { TskTitle } from "../../base/title/title.component";
import { TskText } from "../../base/text/text.component";
import { Badge } from "../../badges/badge/badge.component";
import { TskLabel } from "../../base/label/label.component";
import { Subtitle } from "../../base/subtitle/subtitle.component";

@Component({
  selector: 'chat-card',
  standalone: true,
  imports: [
    Avatar,
    TskTitle,
    Badge,
    Subtitle
],
  templateUrl: './chat-card.component.html',
  styleUrl: './chat-card.component.scss'
})
export class ChatCard {

}

// src/components/cards/ChatCard/index.tsx
import { Badge } from "../../badge/Badge";
import { Subtitle } from "../../base/Subtitle";
import { Title } from "../../base/Title";
import { Avatar } from "../../misc/Avatar";
import { Container, Leading } from "./style";

export function ChatCard() {
  return (
    <Container className="chat-card">
      <Leading className="chat-leading">
        <Avatar online={false} size="small" image=""/>
        <div id="texts">
          <Title>Nome do chat</Title>
          <Subtitle>Mensagem</Subtitle>
        </div>
      </Leading>
      <Badge>+n</Badge>
    </Container>
  )
}
