// react/src/screens/Project/Overview/index.tsx
import { Badge } from "../../../components/badge/Badge";
import { DateBadge } from "../../../components/badge/DateBadge";
import { Label } from "../../../components/base/Label";
import { Text } from "../../../components/base/Text";
import { Title } from "../../../components/base/Title";
import { CommentCard } from "../../../components/cards/CommentCard";
import { TaskCard } from "../../../components/cards/TaskCard";
import { ImportantDates } from "../../../components/ImportantDates";
import { Scroller } from "../../../components/misc/Scroller";
import { User } from "../../../components/misc/User";
import { Abstract, AbstractItem, Comments, Container, Content, ImportantTasks, ProjectInfo } from "./style";

export function Overview() {
  const tasks = Array.from({length: 10}, (_, i) => i);

  return (
    <Container className="overview">
      <Abstract className="abstract">
        <ProjectInfo>
          <div id="leading">
            <Title>Project name</Title>
            <Text>description</Text>
          </div>
          <Badge>Pending</Badge>
        </ProjectInfo>
        <AbstractItem className="abstract-item">
          <Label>Owner</Label>
          <User />
        </AbstractItem>
        <AbstractItem className="abstract-item">
          <Label>Due date</Label>
          <DateBadge />
        </AbstractItem>
      </Abstract>
      <Content className="content">
        {/* <project-menu /> */}
        <ImportantTasks className="important-tasks">
          <Title>Most important</Title>
          <Scroller className="horizontal">
            {
              tasks.map((_) => <TaskCard title="Task" description="Description"/>)
            }
          </Scroller>
        </ImportantTasks>
        <Comments className="overview-comments">
          <Title>Comments</Title>
          <div id="cards">
            {
              tasks.map((_) => <CommentCard/>)
            }
          </div>
        </Comments>
      </Content>
      <ImportantDates/>
    </Container>
  )
}

// src/app/pages/project-page/overview/overview.component.ts
import { Component, Input } from '@angular/core';
import { User } from '../../../components/user/user.component';
import { TskDateBadge } from '../../../components/badges/date-badge/date-badge.component';
import { CircularProgressBar } from '../../../components/misc/c-progress-bar/c-progress-bar.component';
import { TaskCard } from '../../../components/cards/task-card/task-card.component';
import { MessageCard } from '../../../components/cards/message/message.component';
import { ImportantDates } from '../../../components/misc/important-dates/important-dates.component';
import { ProjectMenu } from '../../../components/toolbars/project-menu/project-menu.component';
import { TskText } from '../../../components/base/text/text.component';
import { TskTitle } from '../../../components/base/title/title.component';
import { ScrollerComponent } from '../../../components/misc/scroller/scroller.component';
import { Badge } from '../../../components/badges/badge/badge.component';
import { CommentCard } from '../../../components/cards/comment-card/comment-card.component';
import { TskLabel } from '../../../components/base/label/label.component';

@Component({
  selector: 'app-overview',
  standalone: true,
  imports: [
    User,
    TskDateBadge,
    TaskCard,
    ImportantDates,
    ProjectMenu,
    TskText,
    TskTitle,
    ScrollerComponent,
    Badge,
    CommentCard,
    TskLabel
  ],
  templateUrl: './overview.component.html',
  styleUrl: './overview.component.scss'
})
export class OverviewComponent {
  tasks = Array.from({ length: 12 }, (_, i) => i);
}

<div class="overview">
  <div class="abstract">
    <div class="abstract-item project-infos">
      <div id="leading">
        <tsk-title>Project name</tsk-title>
        <tsk-text>description</tsk-text>
      </div>
      <badge content="Pending"/>
    </div>
    <div class="abstract-item">
      <tsk-label>Owner</tsk-label>
      <user/>
    </div>
    <div class="abstract-item">
      <tsk-label>Due date</tsk-label>
      <tsk-date-badge/>
    </div>
  </div>
  <div class="content">
    <project-menu />
    <div class="important-tasks">
      <tsk-title>Most important</tsk-title>
      <scroller axis="horizontal">
        @for (task of tasks; track task) {
          <task-card/>
        }
      </scroller>
    </div>
    <div class="comments">
      <tsk-title>Comments</tsk-title>
      <div id="cards">
        @for (task of tasks; track task) {
          <comment-card/>
        }
      </div>
    </div>
  </div>
  <important-dates id="important-dates"/>
</div>
