// src/app/components/cards/comment-card/comment-card.component.ts
import { Component } from '@angular/core';
import { TskDateBadge } from '../../badges/date-badge/date-badge.component';
import { Avatar } from '../../misc/avatar/avatar.component';
import { TskTitle } from '../../base/title/title.component';
import { Subtitle } from '../../base/subtitle/subtitle.component';
import { TskText } from '../../base/text/text.component';
import { TskLabel } from '../../base/label/label.component';

@Component({
  selector: 'comment-card',
  standalone: true,
  imports: [
    Avatar,
    TskText,
    TskLabel,
    Subtitle
  ],
  templateUrl: './comment-card.component.html',
  styleUrl: './comment-card.component.scss'
})
export class CommentCard {

}

<div class="comment-card">
  <div class="indicator">
    <div class="flag"></div>
  </div>
  <div id="content">
    <avatar size="medium"/>
    <div id="text">
      <div id="message-label">
        <tsk-label>Username</tsk-label>
       <subtitle>, in mm 00, aaaa</subtitle>
      </div>
      <tsk-text>Message</tsk-text>
    </div>
  </div>
</div>

// src/components/cards/CommentCard/index.tsx
import { Label } from "../../base/Label";
import { Subtitle } from "../../base/Subtitle";
import { Text } from "../../base/Text";
import { Avatar } from "../../misc/Avatar";
import { Flag, Indicator } from "../TaskCard/style";
import { Card, Container, Texts } from "./style";

export function CommentCard() {
  return (
    <Card className="comment-card">
      <Indicator className="indicator">
        <Flag/>
        <div className="flag"></div>
      </Indicator>
      <Container id="comment-leading">
        <Avatar size="medium" image=""/>
        <div id="text">
          <Texts id="message-label">
            <Label>Username</Label>
            <Subtitle>, in mm 00, aaaa</Subtitle>
          </Texts>
          <Text>Message</Text>
        </div>
      </Container>
    </Card>
  )
}
