// react/src/screens/Project/Events/index.tsx
import { CreateButton } from "../../../components/buttons/CreateButton";
import { ProjectMenu } from "../../../components/ProjectMenu";
import { CalendarArea, Container, Header } from "./style";
import { Calendar } from "../../../components/misc/Calendar";

export function Events() {
  return (
    <Container className="calendar-page">
      <Header id="calendar-header">
        <ProjectMenu />
        <CreateButton>New Task</CreateButton>
      </Header>
      <CalendarArea id="calendar-area">
        <Calendar />
      </CalendarArea>
    </Container>
  )
}

// angular/src/app/pages/project-page/events/events.component.ts
import { Component } from '@angular/core';
import { ProjectMenu } from '../../../components/toolbars/project-menu/project-menu.component';
import { CreateButton } from '../../../components/buttons/create-btn/create-btn.component';
import { Calendar } from '../../../components/misc/calendar/calendar.component';

@Component({
  selector: 'app-calendar',
  standalone: true,
  imports: [
    ProjectMenu,
    CreateButton,
    Calendar
  ],
  templateUrl: './events.component.html',
  styleUrl: './events.component.scss'
})
export class Events {

}

<div class="events">
  <div id="header">
    <project-menu/>
    <create-btn>New Task</create-btn>
  </div>
  <div id="calendar">
    <calendar/>
  </div>
</div>
