// angular/src/app/components/toolbars/nav-bar/nav-bar.component.ts
import { Component } from '@angular/core';
import { NgIconComponent, NgIconsModule, provideIcons } from '@ng-icons/core';
import { heroArrowLeftStartOnRectangleSolid, heroBuildingOfficeSolid, heroChatBubbleOvalLeftSolid, heroCog6ToothSolid, heroInboxStackSolid, heroUsersSolid, heroWindowSolid } from '@ng-icons/heroicons/solid';
import { Router } from '@angular/router';

@Component({
  selector: 'nav-bar',
  standalone: true,
  imports: [
    NgIconComponent
  ],
  providers: [ provideIcons({ 
    heroWindowSolid,
    heroInboxStackSolid,
    heroCog6ToothSolid,
    heroChatBubbleOvalLeftSolid,
    heroArrowLeftStartOnRectangleSolid,
    heroUsersSolid
  }) ],
  templateUrl: './nav-bar.component.html',
  styleUrl: './nav-bar.component.scss'
})
export class NavBarComponent {
  constructor (
    private readonly router: Router
  ){}
  page: 'workspace' | 'projects' | 'inbox' | 'affiliations' = 'workspace';

  go(page: 'workspace' | 'projects' | 'inbox' | 'affiliations') {
    console.log(`go to ${page}`);
    this.page = page;
    this.router.navigate([`home/${page}`]);
  }
}

<div class="nav-bar">
  <nav>
    <button class="nav-item" type="button" (click)="go('workspace')">
      <ng-icon name="heroWindowSolid" size="18"></ng-icon>
      Workspace
    </button>
    <button class="nav-item" type="button" (click)="go('projects')">
      <ng-icon name="heroInboxStackSolid" size="18"></ng-icon>
      Projects
    </button>
    <button class="nav-item" type="button" (click)="go('inbox')">
      <ng-icon name="heroChatBubbleOvalLeftSolid" size="18"></ng-icon>
      Inbox
    </button>
    <button class="nav-item" type="button" (click)="go('affiliations')">
      <ng-icon name="heroUsersSolid" size="18"></ng-icon>
      Affiliations
    </button>
  </nav>
  <div class="actions">
    <button class="nav-item">
      <ng-icon name="heroCog6ToothSolid" size="18"></ng-icon>
      Settings
    </button>
    <button class="nav-item log-out">
      <ng-icon name="heroArrowLeftStartOnRectangleSolid" size="18"></ng-icon>
      Logout
    </button>
  </div>
</div>

// react/src/components/toolbars/NavBar/index.tsx
import { ArrowLeftStartOnRectangleIcon } from "@heroicons/react/16/solid"
import { ChatBubbleOvalLeftIcon, Cog6ToothIcon, InboxStackIcon, UsersIcon, WindowIcon } from "@heroicons/react/24/solid"
import Palette from "../../../assets/palette"
import { Actions, Container, Nav, NavItem } from "./style"
import { useNavigate } from "react-router-dom"

export function NavBar() {
  const navigate = useNavigate();

  return (
    <Container className="nav-bar">
      <Nav>
        <NavItem className="nav-item" type="button" onClick={() => navigate('workspace')}>
          <WindowIcon width="18" />
          Workspace
        </NavItem>
        <NavItem className="nav-item" type="button" onClick={() => navigate('projects')}>
          <InboxStackIcon width="18"/>
          Projects
        </NavItem>
        <NavItem className="nav-item" type="button" onClick={() => navigate('inbox')}>
          <ChatBubbleOvalLeftIcon width="18"/>
          Inbox
        </NavItem >
        <NavItem className="nav-item" type="button" onClick={() => navigate('social')}>
          <UsersIcon width="18"/>
          Affiliations
        </NavItem >
      </Nav>
        <Actions className="actions">
          <NavItem className="nav-item">
            <Cog6ToothIcon width="18"/>
            Settings
          </NavItem>
          <NavItem className="nav-item log-out" onClick={() => navigate('/login')}>
            <ArrowLeftStartOnRectangleIcon width="18" color={Palette.red}/>
            Logout
          </NavItem>
        </Actions>
    </Container>
  )
}
