// src/components/cards/ProjectCard/index.tsx
import { Subtitle } from "../../base/Subtitle";
import { Title } from "../../base/Title";
import { Badge } from "../../badge/Badge";
import { Card, Leading, Trailing } from "./style";
import { DateBadge } from "../../badge/DateBadge";
import { useNavigate } from "react-router-dom";
import { DateTime } from "luxon";
import type { ProjectProgress } from "../../../service/types/project/project.dto";

interface ProjectCardProps {
  id: string;
  title: string;
  description: string;
  due_date: string;
  progress: ProjectProgress;
}

export function ProjectCard(props: ProjectCardProps) {
  const navigate = useNavigate();

  const goToProjectPage = () => navigate(`/home/project/${props.id}/overview`)

  return (
    <Card className="project-card" onClick={goToProjectPage}>
      <Leading className="card-leading">
        <div className="text">
          <Title>{props.title}</Title>
          <Subtitle>{props.description}</Subtitle>
        </div>
        <DateBadge
          date={DateTime.fromISO(props.due_date)}
        />
      </Leading>
      <Trailing className="card-Trailing">
        <Badge>{props.progress}</Badge>
        {/* <team /> */}
      </Trailing>
    </Card >
  )
}

// src/app/components/cards/project-card/project-card.component.ts
import { Component, Input } from '@angular/core';
import { TskDateBadge } from '../../badges/date-badge/date-badge.component';
import { Team } from '../../team/team.component';
import { Project } from '../../../service/project';
import { Router } from '@angular/router';
import { Subtitle } from "../../base/subtitle/subtitle.component";
import { TskTitle } from "../../base/title/title.component";
import { Badge } from "../../badges/badge/badge.component";

@Component({
  selector: 'project-card',
  standalone: true,
  imports: [
    TskDateBadge,
    Team,
    Subtitle,
    TskTitle,
    Badge
],
  templateUrl: './project-card.component.html',
  styleUrl: './project-card.component.scss'
})
export class ProjectCard {
  constructor (private router: Router) {}
  
  @Input() data: Project = {
    title: 'projeto',
    description: 'projeto teste'
  };

  openProject() {
    console.log('clicado');
    
    this.router.navigate(['/home/project']);
  }
}

<div class="project-card" (click)="openProject()">
  <div class="tsk-leading">
    <div class="text">
      <tsk-title>{{ data.title }}</tsk-title>
      <subtitle>{{ data.description }}</subtitle>
    </div>
    <tsk-date-badge/>
  </div>
  <div class="tsk-trealing">
    <badge content="Pending"/>
    <team/>
  </div>
</div>
