// angular/src/app/components/misc/avatar/avatar.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'avatar',
  standalone: true,
  imports: [
    CommonModule
  ],
  templateUrl: './avatar.component.html',
  styleUrl: './avatar.component.scss'
})
export class Avatar {
  @Input() size: 'small' | 'large' | 'medium' = 'medium';

  @Input() online: boolean = false;

  get Size(): string {
    return `avtr-${this.size}`;
  }
}

<div [ngClass]="{ 'indicator': online }">
  <div [ngClass]="Size"></div>
</div>

// react/src/components/misc/Avatar/index.tsx
import { Container, Image, Indicator } from "./style.ts";

interface AvatarProps {
  image: string;
  size: 'small' | 'medium' | 'large';
  online?: boolean;
}

export function Avatar(props: AvatarProps) {
  return (
    <Indicator online={props.online ?? false}>
      <Container className={`avatar ${props.size}`}>
        { props.image !== "" ? <Image src={props.image}/> : <></>}
      </Container>
    </Indicator>
  )
}
