// angular/src/app/components/toolbars/app-bar/app-bar.component.ts
import { Component } from '@angular/core';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { heroBellSolid, heroClipboardSolid } from '@ng-icons/heroicons/solid';
import { Avatar } from '../../misc/avatar/avatar.component';
import { Router } from '@angular/router';
import { LogoIcon } from "../../icons/logo-icon/logo-icon.component";

@Component({
  selector: 'app-bar',
  standalone: true,
  imports: [
    NgIconComponent,
    Avatar,
    LogoIcon
],
  providers: [ 
    provideIcons({ 
      heroBellSolid,
      heroClipboardSolid
    })
  ],
  templateUrl: './app-bar.component.html',
  styleUrl: './app-bar.component.scss'
})
export class AppBar {
  constructor (private router: Router) {}

  goToProfile() {
    this.router.navigate(['/home/profile']);
  }

}

// src/components/toolbars/AppBar/index.tsx
import { LogoIcon } from "../../images/LogoIcon";
import Icon from "../../../assets/icons/favicon.svg";
import { BellIcon } from "@heroicons/react/24/solid";
import { Title } from "../../base/Title";
import { Container, Logo, UserInfos } from "./style";
import { Avatar } from "../../misc/Avatar";
import { useNavigate } from "react-router-dom";

export function AppBar() {
  const navigate = useNavigate();
  
  const goToProfile = () => {
    navigate('/home/profile')
  }

  return (
    <Container className="tskr-app-bar">
      <Logo className="tskr-appbar-logo">
        <LogoIcon source={Icon}/>
        <Title>Tasker</Title>
      </Logo>
      <UserInfos className="tskr-user-infos">
        {/* <BellIcon width={28}/> */}
        <button type="button" onClick={goToProfile}>
          <Avatar online={false} image="" size="medium"/>
        </button>
      </UserInfos>
    </Container>
  )
}
