// react/src/components/ProjectMenu/index.tsx
import { UserGroupIcon } from "@heroicons/react/16/solid"
import { CalendarIcon, ClipboardIcon, WindowIcon } from "@heroicons/react/24/solid"
import { Button, Container } from "./style"
import { Text } from "../base/Text"
import { useNavigate } from "react-router-dom"

export function ProjectMenu() {
  const navigate = useNavigate();
  
  return (
    <Container className="project-menu">
      <Button onClick={() => navigate('/home/project/overview')}>
        <WindowIcon width="20"/>
        <Text>Overview</Text>
      </Button>
      <Button onClick={() => navigate('/home/project/tasks')}>
        <ClipboardIcon width="20"/>
        <Text>Tasks</Text>
      </Button >
      <Button onClick={() => navigate('/home/project/members')}>
        <UserGroupIcon width="20"/>
        <Text>Members</Text>
      </Button >
      <Button onClick={() => navigate('/home/project/calendar')}>
        <CalendarIcon width="20"/>
        <Text>Calendar</Text>
      </Button >
    </Container >
  )
}

// angular/src/app/components/toolbars/project-menu/project-menu.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { heroUserGroupMini } from '@ng-icons/heroicons/mini';
import { heroCalendarSolid, heroClipboardSolid, heroWindowSolid } from '@ng-icons/heroicons/solid';

@Component({
  selector: 'project-menu',
  standalone: true,
  imports: [
    NgIconComponent
  ],
  providers: [
    provideIcons({
      heroWindowSolid,
      heroClipboardSolid,
      heroUserGroupMini,
      heroCalendarSolid
    })
  ],
  templateUrl: './project-menu.component.html',
  styleUrl: './project-menu.component.scss'
})
export class ProjectMenu {
  constructor (private router: Router){};
  
  gotTo(page:string) {
    this.router.navigate([`home/project/${page}`])
  }
}

<div class="project-menu">
  <button (click)="gotTo('overview')">
    <ng-icon name="heroWindowSolid" size="20"></ng-icon>
    Overview
  </button>
  <button (click)="gotTo('tasks')">
    <ng-icon name="heroClipboardSolid" size="20"></ng-icon>
    Tasks
  </button>
  <button (click)="gotTo('members')">
    <ng-icon name="heroUserGroupMini" size="20"></ng-icon>
    Members
  </button>
  <button (click)="gotTo('calendar')">
    <ng-icon name="heroCalendarSolid" size="20"></ng-icon>
    Calendar
  </button>
</div>
