// src/app/pages/project-page/members/members.component.ts
import { Component } from '@angular/core';
import { ProjectMenu } from '../../../components/toolbars/project-menu/project-menu.component';
import { CreateButton } from '../../../components/buttons/create-btn/create-btn.component';
import { SearchComponent } from '../../../components/misc/search-field/search.component';
import { User } from '../../../components/user/user.component';
import { Badge } from '../../../components/badges/badge/badge.component';

@Component({
  selector: 'app-members',
  standalone: true,
  imports: [
    ProjectMenu,
    CreateButton,
    SearchComponent,
    User,
    Badge
  ],
  templateUrl: './members.component.html',
  styleUrl: './members.component.scss'
})
export class MembersComponent {
  members = Array.from({ length: 4 }, (_, i) => i);
}

<div class="members">
  <div id="header">
    <project-menu/>
    <create-btn>Add member</create-btn>
  </div>
  <search-field/>
  <div id="team">
    <div id="team-header">
      <div id="header-cell">User</div>
      <div id="header-cell">Role</div>
      <div id="header-cell">Tasks</div>
    </div>
    <div id="body">
      <div id="member">
        <user/>
        <badge content="Owner"/>
        <div id="total-tasks">00 out of 00</div>
      </div>

      @for (members of members; track $index) {
        <div id="member">
          <user/>
          <badge content="Member" color="blue"/>
          <div id="total-tasks">00 out of 00</div>
        </div>
      }
    </div>
  </div>
</div>

// react/src/screens/Project/Members/index.tsx
import { Title } from "../../../components/base/Title";
import { CreateButton } from "../../../components/buttons/CreateButton";
import { Scroller } from "../../../components/misc/Scroller";
import { ProjectMenu } from "../../../components/ProjectMenu";
import { SearchField } from "../../../components/textfields/SearchField";
import { MemberTile } from "../../../components/tiles/MemberTile";
import { Container, Content, ContentHeader, Header, MembersArea } from "./style";

export function Members() {
  const members = Array.from({ length: 10 }, (_, i) => i);

  return (
    <Container className="members">
      <Header id="header">
        <ProjectMenu />
        <CreateButton>Add member</CreateButton>
      </Header>
      <SearchField filter sort/>
      <Content id="team">
        <ContentHeader id="team-header">
          <Title>User</Title>
          <Title>Role</Title>
          <Title>Tasks</Title>
        </ContentHeader>
        <MembersArea>
          <Scroller className='vertical'>
            <MemberTile type="owner" tasks={{done: '00', total: '000'}}/>

            {
              members.map((index) => <MemberTile key={index} type="member" tasks={{done: '00', total: '000'}}/>)
            }
          </Scroller>
        </MembersArea>
      </Content>
    </Container>
  )
}
