// angular/src/app/components/misc/calendar/event-accordion/event-accordion.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { heroCalendarMini, heroChevronDownMini } from '@ng-icons/heroicons/mini';
import { CalendarTag } from '../calendar-tag/calendar-tag.component';
import { DateTime } from 'luxon';

@Component({
  selector: 'event-accordion',
  standalone: true,
  imports: [
    NgIconComponent,
    CommonModule,
    CalendarTag
  ],
  providers: [
    provideIcons({
      heroChevronDownMini,
      heroCalendarMini
    })
  ],
  templateUrl: './event-accordion.component.html',
  styleUrl: './event-accordion.component.scss'
})
export class EventAccordion implements OnInit, OnChanges {
  private today: DateTime = DateTime.local();

  @Input() date: {
    day: string,
    month: string,
    year: string
  } = {
    day: '',
    month: '',
    year: ''
  }

  contentOn: boolean = false;

  ngOnInit(): void {
    this.contentOn = this.isToday();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (this.sameMonth() && this.isToday()) {
      this.contentOn = true;
      return;
    }
    this.contentOn = false;
  }

  showContent() {
    console.log('showing content? '+this.contentOn);
    
    this.contentOn = !this.contentOn;
  }

  isToday(): boolean {
    return this.date.day === this.today.day.toString()
            &&
           this.sameMonth()
             ? true
             : false
  }

  sameMonth(): boolean {
    return this.date.month.toLowerCase() === this.today.monthShort?.replace('.', '')
            ? true
            : false
  }
}

<div id="day">
  <div id="accordion" (click)="showContent()">
    <p [ngClass]="{ 'activated': isToday() }">
      <ng-icon name="heroCalendarMini"></ng-icon>
      {{date.day}} {{date.month}}, {{date.year}}
    </p>
    <ng-icon name="heroChevronDownMini" size="22" color="blue"></ng-icon>
  </div>
  <div id="content"
    [ngClass]="{
      'content-off': !contentOn,
      'content-on': contentOn
    }">
    <calendar-tag/>
    <calendar-tag type="event"/>
  </div>
</div>

// react/src/components/misc/Calendar/EventAccordion/index.tsx
import { ChevronDownIcon } from "@heroicons/react/16/solid";
import { CalendarIcon } from "@heroicons/react/24/solid";
import { DateTime } from "luxon";
import { useEffect, useState } from "react";
import { Accordion, Activated, Content, Tag } from "./style";
import { CalendarTag } from "../CalendarTag";

interface EventAccordionProps {
  day: string,
  month: string | undefined,
  year: string,
  today: boolean
}

export function EventAccordion(props: EventAccordionProps) {
  const today = DateTime.local();
  const [contentOn, setContentOn] = useState(false);

  const showContent = () => {
    setContentOn(!contentOn);
  }

  const isToday = (): boolean => {
    return props.day === today.day.toString()
            &&
           sameMonth()
             ? true
             : false
  }

  const sameMonth = (): boolean => {
    return props.month === today.monthShort
            ? true
            : false
  }

  useEffect(() => {
    setContentOn(isToday())
  }, []);

  return (
    <Tag id="day">
      <Accordion id="accordion" onClick={showContent}>
        <Activated activated={isToday()}>
          <CalendarIcon width='20'/>
          {props.day} {props.month} {props.year}
        </Activated>
        <ChevronDownIcon width="22" color="blue" />
      </Accordion>
      {
        contentOn
          ? <Content id="accordion-content">
            <CalendarTag />
            <CalendarTag type="event" />
          </Content>
          : <></>
      }
    </Tag >
  )
}
