// src/components/misc/Calendar/index.tsx
import { useEffect, useRef, useState } from "react";
import { DateTime, Info, Interval } from 'luxon';
import { Title } from "../../base/Title";
import { ChevronLeftIcon, ChevronRightIcon, ClipboardIcon, FlagIcon } from "@heroicons/react/16/solid";
import { Active, Container, Day, Today, Weekday, Header, Weeks, Weekdays, Events } from "./style";
import Palette from "../../../assets/palette";
import { EventAccordion } from "./EventAccordion";
import type { EventDTO } from "../../../service/types/events/event.dto";

type Month = {
  name: string;
  short: string;
}

interface DayCardProps {
  isToday: boolean;
  isActive: boolean;
  content: number;
  // haveTasks: Function;
  events: EventDTO[];
}

function DayCard(props: DayCardProps) {
  const haveEvents = () => {
    return props.events.length > 0;
  }

  return (
    <Day>
      { props.isToday
        ? <Today>{props.content}</Today>
        : <Active isActive={props.isActive}>{props.content}</Active>
      }
      {<div id="indicators">
        {
          /* props.haveTasks() ? <ClipboardIcon width={16} /> : <></> */
        }
        {
          haveEvents() ? <FlagIcon width={16} /> : <></>
        }
      </div>}
    </Day>
  )
}

interface CalendarProps {
  events: EventDTO[]
}

export function Calendar({
  events
}: CalendarProps) {
  const today = DateTime.now();
  const [month, setMonth] = useState<Month>({
    short: today.monthShort!,
    name: today.monthLong
  });
  const [days, setDays] = useState<DateTime[]>([]);
  const [weekdays, setWeekdays] = useState<string[]>([]);
  const [firstDay, setFirstDay] = useState<DateTime>(today.startOf('month'));

  const containerRef = useRef<HTMLDivElement>(null);

  const isToday = () => {
    return today.hasSame(today, 'day');
  }

  const prevMonth = () => {
    setFirstDay(firstDay?.minus({ month: 1 }));
  }

  const nextMonth = () => {
    setFirstDay(firstDay?.plus({ month: 1 }));
  }

  const updateMonth = () => {
    const name = firstDay?.monthLong as string;

    const short = firstDay?.monthShort as string;

    setMonth({
      name: name[0].toUpperCase() + name.substring(1).toLowerCase(),
      short: short[0]
    });
  }
  useEffect(updateMonth, [firstDay]);

  const updateDays = () => {
    const d = Interval.fromDateTimes(
      firstDay?.startOf('week'),
      firstDay?.endOf('month').endOf('week')
    ).splitBy({ day: 1 }).map(
      (day) => {
        if (day.start === null) {
          throw new Error('Wrong dates')
        }
        return day.start;
      }
    );
    setDays(d);
  }
  useEffect(updateDays, [month]);

  useEffect(() => {
    if (containerRef.current) {
      const todayElement = containerRef.current.querySelector("[today='true']");
      if (todayElement) {
        (todayElement as HTMLElement).scrollIntoView({
          behavior: 'smooth',
          block: 'start',
        })
      }
    }

    const weeks = Info.weekdays('short').map(
      (weekday) => weekday[0].toUpperCase() + weekday.substring(1).toLowerCase().replace('.', '')
    )
    setWeekdays(
      weeks
    );
    updateMonth()
  }, [])

  return (
    <Container className="calendar">
      <Header id="calendar-header">
        <Title>{month?.name}, {firstDay?.year}</Title>
        <div id="actions">
          <button type="button" onClick={prevMonth}>
            <ChevronLeftIcon width="32" fill={Palette.gray}/>
          </button>
          <button type="button" onClick={nextMonth}>
            <ChevronRightIcon width="32" fill={Palette.gray}/>
          </button>
        </div>
      </Header >
      <Weeks id="weeks">
        <Weekdays id="weekdays">
          {
            weekdays?.map(
              (weekday, i) => <Weekday key={i}>
                {weekday}
                {days?.map(
                  (day, index) => 
                    day.weekday === (weekdays.indexOf(weekday) + 1) ? 
                    <DayCard key={index}
                      isToday={day.day === today?.day && day.month === today?.month}
                      isActive={day.month === firstDay?.month}
                      content={day.day}
                      events={events.filter(evt => DateTime.fromISO(evt.date, { zone: 'utc' }).hasSame(day, 'day'))}
                    /> : <></>
                )}
              </Weekday>
            )
          }
        </Weekdays>
      </Weeks>
      <Events
        id="events"
        ref={containerRef}
      >
        {
          days?.map((date) => <EventAccordion
                            day={date.day.toString()}
                            month={date.monthShort!}
                            year={date.year.toString()}
                            today={isToday()}
                            events={events.filter(evt => DateTime.fromISO(evt.date, { zone: 'utc' }).hasSame(date, 'day'))}
                         />
                  )
        }
      </Events>
    </Container >
  )
}

// angular/src/app/components/misc/calendar/calendar.component.ts
import { CommonModule } from '@angular/common';
import { Component, Inject, Input, signal, Signal } from '@angular/core';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { heroChevronDownMini, heroChevronLeftMini, heroChevronRightMini, heroClipboardMini, heroFlagMini } from '@ng-icons/heroicons/mini';
import { DateTime, Info, Interval } from 'luxon';
import { CalendarTag } from './calendar-tag/calendar-tag.component';
import { EventAccordion } from './event-accordion/event-accordion.component';

@Component({
  selector: 'calendar',
  standalone: true,
  imports: [
    NgIconComponent,
    CommonModule,
    CalendarTag,
    EventAccordion
  ],
  providers: [
    provideIcons({
      heroChevronLeftMini,
      heroChevronRightMini,
      heroChevronDownMini,
      heroClipboardMini,
      heroFlagMini
    })
  ],
  templateUrl: './calendar.component.html',
  styleUrl: './calendar.component.scss'
})
export class Calendar {
  @Input() class: string = '';

  today: DateTime = DateTime.local();

  weekdays: string[] = Info.weekdays('short').map(
    (weekday) => weekday[0].toUpperCase() + weekday.substring(1).toLowerCase().replace('.', '')
  );

  firstDay: DateTime = this.today.startOf('month');

  get days() {
    const d = Interval.fromDateTimes(
      this.firstDay.startOf('week'),
      this.firstDay.endOf('month').endOf('week')
    ).splitBy({ day: 1 }).map(
      (day) => {
        if (day.start === null) {
          throw new Error('Wrong dates')
        }
        return day.start;
      } 
    );
    return d;
  }
  
  get month(): { name: string, short: string} {
    const name = this.firstDay.monthLong as string;

    const short = this.firstDay.monthShort as string;

    return {
      name: name[0].toUpperCase() + name.substring(1).toLowerCase(),
      short: short[0].toUpperCase() + short.substring(1).toLowerCase().replace('.', '')
    };
  }

  get haveTasks() {
    return false;
  }

  get haveEvents() {
    return false;
  }

  nextMonth() {
    this.firstDay = this.firstDay.plus({ month: 1 });
  }

  prevMonth() {
    this.firstDay = this.firstDay.minus({ month: 1 });
  }
}

<div class="calendar">
  <div id="header">
    <h6>{{month.name}}, {{firstDay.year}}</h6>
    <div id="actions">
      <button type="button" (click)="prevMonth()">
        <ng-icon name="heroChevronLeftMini" size="32"></ng-icon>
      </button>
      <button type="button" (click)="nextMonth()">
        <ng-icon name="heroChevronRightMini" size="32" ></ng-icon>
      </button>
    </div>
  </div>
  <div id="weeks">
    <div id="weekdays">
      @for (weekday of weekdays; track $index) {
        <ul id="weekday">
          {{weekday}}
          @for (day of days; track $index) {
            @if (day.weekday === (weekdays.indexOf(weekday)+1)) {
              <li id="day"
                [ngClass]="{
                  'today': day.day === today.day && day.month === today.month,
                  'inactive-day': day.month !== firstDay.month,
                  'active-day': day.month === firstDay.month
                }"
              >
                <p>{{day.day}}</p>
                <div id="indicators">
                  @if (haveTasks) {
                    <ng-icon name="heroClipboardMini"></ng-icon>
                  }
                  @if (haveEvents) {
                    <ng-icon name="heroFlagMini"></ng-icon>
                  }
                </div>
              </li>
            }
          }
        </ul>
      }
    </div>
  </div>
  <div id="events">
    @for (date of days; track $index) {
      <event-accordion [date]="{
        day: date.day.toString(),
        month: month.short,
        year: firstDay.year.toString()
      }"/>
    }
  </div>
</div>
