// react/src/components/ImportantDates/index.tsx
import { Subtitle } from "../base/Subtitle"
import { Text } from "../base/Text"
import { Title } from "../base/Title"
import { Scroller } from "../misc/Scroller"
import { Container, Day, Event, Month, Name } from "./style"

export function ImportantDates() {
  const events = Array.from({length: 4}, (_,i)=>i);
  const months: { events: number[] }[] = [
    {
      events: events
    },
    {
      events: events
    },
    {
      events: events
    },
    {
      events: events
    }
  ]

  return (
    <Container className="important-dates">
      <Title>Important dates</Title>

      <Scroller className="vertical">
        {
          months.map((day) => 
            <Month id="month">
              <Subtitle>Month, YYYY</Subtitle>

              {
                day.events.map(
                  (_) => <Event id="event">
                          <Day id="day">
                            <Text>Day</Text>
                            <Text>00</Text>
                          </Day>
                          <Name>Title</Name>
                        </Event>
                )
              }
            </Month>
          )
        }
      </Scroller>
    </Container>
  )
}

// angular/src/app/components/misc/important-dates/important-dates.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'important-dates',
  standalone: true,
  imports: [],
  templateUrl: './important-dates.component.html',
  styleUrl: './important-dates.component.scss'
})
export class ImportantDates {
  events = Array.from({length: 4}, (_,i)=>i);
  months: { events: number[] }[] = [
    {
      events: this.events
    },
    {
      events: this.events
    },
    {
      events: this.events
    },
    {
      events: this.events
    }
  ]
}

<div class="important-dates">
  <h6>Important dates</h6>

  <div id="scroller">
    @for (month of months; track month) {
      <div id="month">
        <p id="tag">Month, YYYY</p>
  
        @for (event of month.events; track event) {
          <div id="event">
            <div id="day">
              <p id="name">Day</p>
              <p>00</p>
            </div>
            <h6>Title</h6>
          </div>
        }
      </div>
    }
  </div>
</div>
