// react/src/components/cards/TaskCard/index.tsx
import { Subtitle } from "../../base/Subtitle";
import { Title } from "../../base/Title";
import { DateBadge } from "../../badge/DateBadge";
import { Avatar } from "../../misc/Avatar";
import { Card, Content, Flag, Indicator, Leading } from "./style";

interface TaskCardProps {
  title: string;
  description: string;
}

export function TaskCard(props: TaskCardProps) {
  return (
    <Card className="task-card">
      <Indicator className="indicator">
        <Flag className="flag"></Flag>
      </Indicator>
      <Content id="content">
        <Leading id="leading">
          <div id="text">
            <Title>{props.title}</Title>
            <Subtitle>{props.description}</Subtitle>
          </div>
          <DateBadge />
        </Leading>
        <Avatar online={false} size="small" image="" />
      </Content>
    </Card>
  )
}

// src/app/components/cards/task-card/task-card.component.ts
import { Component } from '@angular/core';
import { TskDateBadge } from '../../labels/date-badge/date-badge.component';
import { Avatar } from '../../misc/avatar/avatar.component';
import { TskTitle } from '../../base/title/title.component';
import { Subtitle } from '../../base/subtitle/subtitle.component';

@Component({
  selector: 'task-card',
  standalone: true,
  imports: [
    TskDateBadge,
    Avatar,
    TskTitle,
    Subtitle
  ],
  templateUrl: './task-card.component.html',
  styleUrl: './task-card.component.scss'
})
export class TaskCard {

}

<div class="task-card">
  <div class="indicator"></div>
  <div id="content">
    <div id="infos">
      <h6>task</h6>
      <tsk-date-badge/>
    </div>
    <avatar size="small"/>
  </div>
</div>
